// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Model_Viaje_And_Relation_ApplicationUser_TipoVehiculo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_Viaje_And_Relation_ApplicationUser_TipoVehiculo));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291631418_Model_Viaje_And_Relation_ApplicationUser_TipoVehiculo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
